---
debug: 
  level: 1
connections: 
  databases: 
    development: 
      driver: mysql
      host: localhost
      port: 3306
      username: 
      password: 
      database: 
      autocommit: false
    deployment: 
      driver: mysql
      host: localhost
      port: 3306
      username: 
      password: 
      database: 
      autocommit: false
  memcached: 
    application: 
      host: localhost
      port: 11211
    session: 
      host: localhost
      port: 11211
dispatcher: 
  class: AXION_DISPATCHER
controller: 
  default: index
action: 
  default: index
model: |
  
  
view: 
  compress: gzip
  striphtml: false
  templatesuffix: tpl
session: 
  handler: memcached
  timeout: 10800
  savepath: 
cache: 
  path: 
  handler: file
  expire: 60
  prefix: axion
  section: application
misc: 
  timezone: Asia/Shanghai
